### Name
spring.application.name=api-aws-java-spring-cloud-v2

### Server
server.port=9094

### Log
logging.file.path=@logs.path@

### Proxy
proxy.host=
proxy.port=
proxy.enabled=

### Spring
server.servlet.context-path=/aws_localstack
server.error.whitelabel.enabled=false
spring.web.resources.add-mappings=false

management.endpoints.web.path-mapping.health=/health
management.endpoints.web.path-mapping.prometheus=/metrics
management.endpoints.web.exposure.include=health, info, metrics
management.endpoints.web.exposure.exclude=env
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.endpoint.prometheus.access=read_only
management.endpoint.metrics.access=read_only

### Info
info.app.name=@artifactId@
info.app.version=@version@
info.app.description=@name@
info.app.contact=
info.app.ip=${spring.cloud.client.ip-address}
info.app.profile=${spring.profiles.active}

##################################################################################################################
# Logs- Info
#logging.level.org.springframework=INFO

# Logs- Debug
logging.level.org.springframework.web=DEBUG

##################################################################################################################
# AWS Service - BOM SDK
aws.region=sa-east-1
aws.dynamodb.endpoint=http://localhost:4566
aws.accessKeyId=dummyKey
aws.secretAccessKey=dummySecret

##################################################################################################################
# AWS Service - SpringCloud
spring.cloud.aws.region.static=sa-east-1
spring.cloud.aws.endpoint=http://localhost:4566
spring.cloud.aws.credentials.access-key=dummy-key
spring.cloud.aws.credentials.secret-key=dummy-secret

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

##################################################################################################################
###########################################
####### AWS SQS Service - Consumer ########
###########################################
fila.receiver.name.sqs-solicitar-regitro-movimento-cliente=sqs-solicitar-regitro-movimento-cliente

##################################################################################################################
###########################################
####### AWS S3 Service - Bucket ########
###########################################
arquivo.s3.bucket.name.bucket-reports-mov-cli=bucket-reports-mov-cli


##################################################################################################################
###########################################
####### AWS SQS Service - Producer ########
###########################################
